=== GA-JC/tcm24twg04/build/data/custos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://tcm24twg04.netlify.app"
    xmlns:tns="https://tcm24twg04.netlify.app"
    elementFormDefault="qualified">

    <xs:element name="custos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="local" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="currency" type="xs:string" />
                            <xs:element name="custo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="item" type="xs:string" />
                                        <xs:element name="valor" type="xs:decimal" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nome" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== GA-JC/tcm24twg04/build/custos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE custos [
    <!ENTITY dollar "&#36;">
    <!ENTITY euro "&#x20AC;">
]>
<custos xmlns="https://tcm24twg04.netlify.app" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://tcm24twg04.netlify.app custos.xsd">
    <local nome="Boston">
        <currency>&dollar;</currency>
        <custo>
            <item>Transporte: Ida e Volta</item>
            <valor>800</valor>
        </custo>
        <custo>
            <item>Alojamento(s)</item>
            <valor>760</valor>
        </custo>
        <custo>
            <item>Alimentação</item>
            <valor>400</valor>
        </custo>
        <custo>
            <item>Deslocação</item>
            <valor>150</valor>
        </custo>
        <custo>
            <item>Atividades</item>
            <valor>90</valor>
        </custo>
        <custo>
            <item>Extras</item>
            <valor>80</valor>
        </custo>
    </local>
    <local nome="Monaco">
        <currency>&euro;</currency>
        <custo>
            <item>Transporte: Ida e Volta</item>
            <valor>572</valor>
        </custo>
        <custo>
            <item>Alojamento(s)</item>
            <valor>877</valor>
        </custo>
        <custo>
            <item>Alimentação</item>
            <valor>350</valor>
        </custo>
        <custo>
            <item>Deslocação</item>
            <valor>200</valor>
        </custo>
        <custo>
            <item>Atividades</item>
            <valor>150</valor>
        </custo>
        <custo>
            <item>Extras</item>
            <valor>175</valor>
        </custo>
    </local>
</custos>
